spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password

  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

logging:
  level:
    com.ecommerce.user: DEBUG

