server:
  port: 8081

spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root


  datasource: # Optional if someone tries to use blocking JPA accidentally
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO

jwt:
  secret: ThisIsAVeryStrongSecretKeyForJWTThatYouStoreInVaultLater
  accessExpiration: 900000
  refreshExpiration: 604800000

